### ISSUE TITLE
Add Topic models to django backend

### ISSUE THREAD

**Issue by to-sta** [to-sta/project#1]
Topics will used to filter/search projects in the future. 

Task:
1. Add `Topics` model in `backend/apps/projects/models.py`
2. Add ManytoMany `FK` to `Projects` model
3. Add the new `topics` field from `Projects` model to `serializer.py`

![image](https://github.com/to-sta/project/assets/49518857/d67ed338-96a1-4daa-9826-8b4abd3d4999)

**Comment by Vayras** [comment]
@to-sta I have create a pull request that hopefully solves this issue
